config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'

  match '/contact', to: "static_pages#contact", via: 'get'

  resources :challenges do
  end
  
  get 'tags/:tag', to: 'challenges#index', as: :tag

end

app/models/challenge.rb
class Challenge < ActiveRecord::Base
	acts_as_taggable

	has_many :videos, dependent: :destroy

	validates :title, presence: true
end

app/models/video.rb
class Video < ActiveRecord::Base
  belongs_to :challenge
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/challenges_controller.rb
class ChallengesController < ApplicationController

#makes a new challenge object
	def new
		@challenge = Challenge.new
	end

#if saves, make new challenge; if not, just render 'new' view page.
	def create
		@challenge = Challenge.new(challenge_params)
		@challenge.score = 0;

		if @challenge.save
			redirect_to challenges_path
		else
			render 'new'
		end

	end

#destroying challenge appropriately
	def destroy
		@challenge = Challenge.find(params[:id])
		@challenge.destroy

		redirect_to challenges_path
	end

	def upvote
		@challenge = Challenge.find(params[:id])
		@challenge.score+=1
		@challenge.save
	end

	def downvote
		@challenge = Challenge.find(params[:id])
		@challenge.score-=1
		@challenge.save
	end

#update action after edit is made
	def update
		@challenge = Challenge.find(params[:id])

		if @challenge.update(challenge_params)
			redirect_to challenges_path
		else
			render 'edit'
		end
	end

#Lists challenges by tags
	def index
		if params[:tag]
			@challenges = Challenge.tagged_with(params[:tag])
		else
			@challenges = Challenge.all
		end
	end

#edits existing challenges
	def edit
		@challenge = Challenge.find(params[:id])
	end

#shows individual challenge
	def show
		@challenge = Challenge.find(params[:id])
	end

#defines strong challenge parameters so only appropriate data is passed
	private
		def challenge_params
			params.require(:challenge).permit(:title, :text, :tag_list, :score, :videos)
		end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
	def home
	end

	def contact
	end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  def new
  	@video = Video.new
  end

  def create
  	@video.string= @challenge.title
        @video.challenge = current_challenge
        if @video.save
          redirect_to challenge_path
        else
          redirect_to root
        end
  end

  def update
  end

  def destroy
  	@video = Video.find(params[:id])
  	@video.destroy

  	redirect_to challenge_path
  end

  private
    
    def video_params
      params.require(:video).permit(:token)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/challenges_helper.rb
module ChallengesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/challenges/_form.html.erb
<%= form_for @challenge, :html => {:multipart => true} do |b| %>

	<p>
		<%= b.label :title %><br>
		<%= b.text_field :title %>
	</p>

	<p>
		<%= b.label :tags %><br>
		<%= b.text_field :tag_list, { :placeholder => "Separate Tags By Commas" } %><br>
	</p>

	<p>
		<%= b.label :text %><br>
		<%= b.text_area :text %><br>

	</p>
	<p>
		<%= b.submit %>
	</p>

<% end %>

app/views/challenges/edit.html.erb
<div id="container">
<h1>Edit Challenge </h1>

<%= render 'form' %>

<%= link_to 'Back', challenges_path %>
</div>

app/views/challenges/index.html.erb
<h1 id="slogan">Compete for Eternal Glory</h1>

<div id="container">
<div id="header">

<div id="newbox">
<%= link_to 'Add', new_challenge_path %>
</div>

<div id="allbox">
	<%= link_to "All", challenges_path %>
</div>

<div id='tag_cloud'>
	<% tag_cloud Challenge.tag_counts, %w[s m l] do |tag, css_class| %>
		<%= link_to tag.name, tag_path(tag.name), class: css_class %>
	<% end %>
</div>
<!--
<div id="search">
	<% form_tag challenges_path, :method => 'get' do %>
	  <p>
	    <%= text_field_tag :search, params[:search] %>
	    <%= submit_tag "Search", :name => nil %>
	  </p>
	<% end %>
</div>
-->
</div>
<br>
<div id="newest">
<% @challenges.each do |challenge| %>
	<span>
		<div id="challengebox">
			<p id="challengetitle">
			<%= link_to challenge.title, challenge_path(challenge) %>
			</p>
			<%= challenge.score %>
			<p id="challengetag">
				<%= raw challenge.tag_list.map { |t| link_to t, tag_path(t) }.join('     ') %>
			</p>
		</div>
	</span>
<% end %>
</div>
<br>
</div>
</div>

app/views/challenges/new.html.erb
<div id="container">
<h1>New Challenge</h1>

<%= render 'form' %>

<%= link_to "Back to the Gauntlet", challenges_path %>
</div>

app/views/challenges/show.html.erb
<div id="container">

<div id="showtitle">
<%= @challenge.title %>
</div>
<div>

<div id="nav">
	<%= link_to 'Home', challenges_path %>
	<%= link_to 'Edit', edit_challenge_path %>
        <!--<%= link_to 'Delete', @challenge, :method => :delete %>
        <%= @challenge.tag_list %>-->
</div>

<p id="showtag">

</p>

<p id="showtext">
	<%= @challenge.text %>
</p>

</div>


</div>

<ul>
  <li>
    <ziggeo class="first" ziggeo-width=320 ziggeo-height=240></ziggeo>
  </li>
</ul>

<script>
  ZiggeoApi.Events.on("submitted", function (data) {
      var flag = 0;
      for (i=0; i<videos.length; i++) {
        if (videos[i].token === data.video.token) {
          flag = 1;
          break;
        }
      }
      if (!flag) {
        videos.push(data.video);
        ZiggeoApi.Videos.update(data.video.token, data, {
          success: function (args, result) {
            //success
          },
          failure: function (args, error) {
            //failure
          }
        });
        element = "<li><ziggeo ziggeo-video='"+ data.video.token + "' ziggeo-width=320 ziggeo-height=240></ziggeo></li>";
        $('ul').append(element);
      }
  });
  
  ZiggeoApi.Events.on("recording", function(data) {
      data.video.key = $('h1').text();
  });

  $( document ).ready(function() {
    var title = $("#showtitle").text();
    if (title === "\nMake a funny face\n"){
      var data = { tags : "funny" };
    }
    else if (title == "\nBest pick up line\n") {
      var data = { tags : 'line' }
    }
    else if (title == "\nBest kiss\n") {
      var data = { tags : 'kiss' };
    }
    else if (title == "\nBest flex\n") {
      var data = { tags : 'flex' };
    }
    else if (title == "\nBest armpit farts\n") {
      var data = { tags : 'armpit' };
    }
    else if (title =="\n30 Second Poem\n") {
      var data = { tags : 'poetry' };
    }
    else if (title == "\nStaring Contest\n") {
      var data = { tags : 'stare' };
    }
    else {
      var data = { tags : 'null' };
    }
    ZiggeoApi.Videos.index(data, {
      success: function (args, result) {
        videos = result;
        for (i=0; i < videos.length; i++) {
          element = "<li><ziggeo ziggeo-video='"+ videos[i].token + "' ziggeo-width=320 ziggeo-height=240></ziggeo></li>";
          $('ul').append(element);
        }
        like_button = "<input type='image' onClick='likeFunction()' style= 'width:4em; height:2em;'src='http://www.insidefacebook.com/wp-content/uploads/2012/07/facebook_like_button_big.jpeg'/>";
        $('ziggeo').append(like_button);
      },
      failure: function (args, error) {
        alert(error);
      }
    });
  });
  
  function likeFunction(){
  }

</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Gauntlet</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>

  <link rel="stylesheet" href="//assets.ziggeo.com/css/ziggeo-betajs-player.min.css" />
  <script src="//assets.ziggeo.com/js/ziggeo-json2-betajs-player.min.js"></script>
  <script>ZiggeoApi.token = "85947ae896bc6363d58e8fdb0025da37";</script>
  
</head>
<body>

<%= yield %>

</body>
</html>

app/views/static_pages/contact.html.erb
<div id="center">
<div id="logo">
	Tom Yang and Arya
</div>
<div id="sword"></div>
<div id="button">
	
</div>
</div>

app/views/static_pages/home.html.erb
<div id="center">
<div id="logo">
	Gauntlet
</div>
<div id="sword"></div>
<div id="button">
	<%= link_to "Enter", challenges_path %>
</div>

<div id="sword1"></div>
<div id="hilt1"></div>
<div id="handle1"></div>

<div id="sword2"></div>
<div id="hilt2"></div>
<div id="handle2"></div>

</div>